package uabc.ic.benjaminbolanos.practica5;

import java.awt.CardLayout;
import java.awt.Color;
import uabc.ic.benjaminbolanos.practica5.listaculturas.VistaCulturas;
import uabc.ic.benjaminbolanos.practica5.memorama.VistaMemorama;

/**
 *
 * @author bbola
 */
public class MainFrame extends javax.swing.JFrame {
    private VistaCulturas culturas;
    private VistaMemorama memorama;
    
    // Indica si la ventana visible es el listado de culturas
    private boolean viendoListado; 
    
    private final Color OSCURO = Color.decode("#1C110A");
    private final Color OSCURO_HOVER = Color.decode("#2D1B10");
    private final Color CLARO = Color.decode("#E4D6A7");
    private final Color CLARO_HOVER = Color.decode("#DBC88A");
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        iniciarCardsPanel();
        viendoListado = true;
    }
    
    private void iniciarCardsPanel(){
        culturas = new VistaCulturas();
        memorama = new VistaMemorama();
        cardsPanel.add(culturas, "Culturas");
        cardsPanel.add(memorama, "Memorama");
    }
    
    private void playground(){
        String[] ar = new String[5];
        ar[0] = "a"; ar[1] = "a"; ar[2] = "a";ar[3] = "a";ar[4] = "a"; 
        for(int i = 0; i < ar.length; i++){
            System.out.println(ar[i]);
        }
        System.out.println("");
        ar[0] = null; ar[3] = null;
        for(int i = 0; i < ar.length; i++){
            
            System.out.println(ar[i]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardsPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        botonMemorama = new javax.swing.JPanel();
        labelMemorama = new javax.swing.JLabel();
        botonListado = new javax.swing.JPanel();
        labelListado = new javax.swing.JLabel();
        labelHechoPor = new javax.swing.JLabel();
        labelAutor = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        cardsPanel.setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(28, 17, 10));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonMemorama.setBackground(new java.awt.Color(28, 17, 10));
        botonMemorama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonMemoramaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonMemoramaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonMemoramaMouseExited(evt);
            }
        });

        labelMemorama.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        labelMemorama.setForeground(new java.awt.Color(228, 214, 167));
        labelMemorama.setText("Memorama");

        javax.swing.GroupLayout botonMemoramaLayout = new javax.swing.GroupLayout(botonMemorama);
        botonMemorama.setLayout(botonMemoramaLayout);
        botonMemoramaLayout.setHorizontalGroup(
            botonMemoramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonMemoramaLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(labelMemorama)
                .addGap(28, 28, 28))
        );
        botonMemoramaLayout.setVerticalGroup(
            botonMemoramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonMemoramaLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(labelMemorama)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanel1.add(botonMemorama, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 180, 120));

        botonListado.setBackground(new java.awt.Color(228, 214, 167));
        botonListado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonListadoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonListadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonListadoMouseExited(evt);
            }
        });

        labelListado.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelListado.setForeground(new java.awt.Color(28, 17, 10));
        labelListado.setText("Listado de Culturas");

        javax.swing.GroupLayout botonListadoLayout = new javax.swing.GroupLayout(botonListado);
        botonListado.setLayout(botonListadoLayout);
        botonListadoLayout.setHorizontalGroup(
            botonListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonListadoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(labelListado)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        botonListadoLayout.setVerticalGroup(
            botonListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonListadoLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(labelListado)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPanel1.add(botonListado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 180, 120));

        labelHechoPor.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        labelHechoPor.setForeground(new java.awt.Color(228, 214, 167));
        labelHechoPor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHechoPor.setText("Hecho Por:");
        jPanel1.add(labelHechoPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 180, 30));

        labelAutor.setFont(new java.awt.Font("Roboto", 1, 21)); // NOI18N
        labelAutor.setForeground(new java.awt.Color(228, 214, 167));
        labelAutor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAutor.setText("Benjamin Bolaños");
        jPanel1.add(labelAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 700, 180, 40));

        labelTitulo.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(228, 214, 167));
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Practica 5");
        jPanel1.add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, 180, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(cardsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1300, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cardsPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonListadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonListadoMouseEntered
        //Efecto hover
        if(!viendoListado){
            botonListado.setBackground(OSCURO_HOVER);
            labelListado.setForeground(CLARO_HOVER);
        }
    }//GEN-LAST:event_botonListadoMouseEntered

    private void botonListadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonListadoMouseExited
        if(!viendoListado){
            botonListado.setBackground(OSCURO);
            labelListado.setForeground(CLARO);
        }
    }//GEN-LAST:event_botonListadoMouseExited

    private void botonMemoramaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMemoramaMouseEntered
        if(viendoListado){
            botonMemorama.setBackground(OSCURO_HOVER);
            labelMemorama.setForeground(CLARO_HOVER);
        }
    }//GEN-LAST:event_botonMemoramaMouseEntered

    private void botonMemoramaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMemoramaMouseExited
        if(viendoListado){
            botonMemorama.setBackground(OSCURO);
            labelMemorama.setForeground(CLARO);
        }
    }//GEN-LAST:event_botonMemoramaMouseExited

    private void botonMemoramaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMemoramaMouseClicked
        if(viendoListado){
            CardLayout cl = (CardLayout) cardsPanel.getLayout();
            cl.show(cardsPanel, "Memorama");
            viendoListado = false;
            botonMemorama.setBackground(CLARO);
            labelMemorama.setForeground(OSCURO);
            botonListado.setBackground(OSCURO);
            labelListado.setForeground(CLARO);
        }
    }//GEN-LAST:event_botonMemoramaMouseClicked

    private void botonListadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonListadoMouseClicked
        if(!viendoListado){
            CardLayout cl = (CardLayout) cardsPanel.getLayout();
            cl.show(cardsPanel, "Culturas");
            viendoListado = true;
            botonListado.setBackground(CLARO);
            labelListado.setForeground(OSCURO);
            botonMemorama.setBackground(OSCURO);
            labelMemorama.setForeground(CLARO);
        }
    }//GEN-LAST:event_botonListadoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botonListado;
    private javax.swing.JPanel botonMemorama;
    private javax.swing.JPanel cardsPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelAutor;
    private javax.swing.JLabel labelHechoPor;
    private javax.swing.JLabel labelListado;
    private javax.swing.JLabel labelMemorama;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables
}
