package uabc.ic.benjaminbolanos.practica5.memorama;

import java.awt.CardLayout;
import javax.swing.ImageIcon;
import uabc.ic.benjaminbolanos.practica5.listascirculares.ListaCircular;
import uabc.ic.benjaminbolanos.practica5.listascirculares.Nodo;

/**
 *
 * @author bbola
 */
public class PanelResultadosMemorama extends javax.swing.JPanel {

    private Nodo<CartaModel> cartaActual;
    
    /**
     * Creates new form VistaCartasMemorama
     */
    public PanelResultadosMemorama() {
        initComponents();
        cartaGrafica1.mostrarContenido();
    }
    
    public void mostrarGuia(){
        CardLayout cl = (CardLayout) mainPanel.getLayout();
        cl.show(mainPanel, "guia");
    }
    
    public void mostrarResultados(ListaCircular<CartaModel> cartas){
        cartaActual = cartas.getInicio();
        cartaGrafica1.setContenido(cartaActual.getInfo());
        CardLayout cl = (CardLayout) mainPanel.getLayout();
        cl.show(mainPanel, "resultados");
    }
    
    private void avanzarCarta(){
        cartaActual = cartaActual.getSig();
        cartaGrafica1.setContenido(cartaActual.getInfo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        panelGuia = new javax.swing.JPanel();
        labelTitulo1 = new javax.swing.JLabel();
        labelTitulo2 = new javax.swing.JLabel();
        labelTitulo3 = new javax.swing.JLabel();
        labelTitulo4 = new javax.swing.JLabel();
        labelTitulo5 = new javax.swing.JLabel();
        labelTitulo6 = new javax.swing.JLabel();
        labelTitulo7 = new javax.swing.JLabel();
        labelTitulo8 = new javax.swing.JLabel();
        labelTitulo9 = new javax.swing.JLabel();
        labelTitulo10 = new javax.swing.JLabel();
        panelResultados = new javax.swing.JPanel();
        cartaGrafica1 = new uabc.ic.benjaminbolanos.practica5.memorama.CartaGrafica();
        labelResultadosTitle = new javax.swing.JLabel();
        btnResultadosSig = new uabc.ic.benjaminbolanos.practica5.BotonLabel();
        labelTitulo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(28, 17, 10));
        setMaximumSize(new java.awt.Dimension(400, 800));
        setMinimumSize(new java.awt.Dimension(400, 800));
        setPreferredSize(new java.awt.Dimension(400, 800));

        mainPanel.setLayout(new java.awt.CardLayout());

        panelGuia.setBackground(new java.awt.Color(28, 17, 10));
        panelGuia.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitulo1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        labelTitulo1.setForeground(new java.awt.Color(228, 214, 167));
        labelTitulo1.setText("-Si la combinación es correcta,");
        panelGuia.add(labelTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        labelTitulo2.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        labelTitulo2.setForeground(new java.awt.Color(228, 214, 167));
        labelTitulo2.setText("Guía Rápida");
        panelGuia.add(labelTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        labelTitulo3.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        labelTitulo3.setForeground(new java.awt.Color(228, 214, 167));
        labelTitulo3.setText("esta pestaña cambia a una con");
        panelGuia.add(labelTitulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, -1, -1));

        labelTitulo4.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        labelTitulo4.setForeground(new java.awt.Color(228, 214, 167));
        labelTitulo4.setText("las cartas desaparecerán");
        panelGuia.add(labelTitulo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        labelTitulo5.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        labelTitulo5.setForeground(new java.awt.Color(228, 214, 167));
        labelTitulo5.setText("-Dale al Botón Realizar Intento");
        panelGuia.add(labelTitulo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        labelTitulo6.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        labelTitulo6.setForeground(new java.awt.Color(228, 214, 167));
        labelTitulo6.setText("-Si no, las cartas volveran a voltearse");
        panelGuia.add(labelTitulo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        labelTitulo7.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        labelTitulo7.setForeground(new java.awt.Color(228, 214, 167));
        labelTitulo7.setText("-Selecciona dos Cartas");
        panelGuia.add(labelTitulo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        labelTitulo8.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        labelTitulo8.setForeground(new java.awt.Color(228, 214, 167));
        labelTitulo8.setText("-Cuando encuentres todos");
        panelGuia.add(labelTitulo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, -1, -1));

        labelTitulo9.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        labelTitulo9.setForeground(new java.awt.Color(228, 214, 167));
        labelTitulo9.setText("los resultados");
        panelGuia.add(labelTitulo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, -1, -1));

        labelTitulo10.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        labelTitulo10.setForeground(new java.awt.Color(228, 214, 167));
        labelTitulo10.setText("los pares, verás como");
        panelGuia.add(labelTitulo10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, -1, -1));

        mainPanel.add(panelGuia, "guia");

        panelResultados.setBackground(new java.awt.Color(28, 17, 10));
        panelResultados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelResultados.add(cartaGrafica1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        labelResultadosTitle.setFont(new java.awt.Font("Roboto", 1, 40)); // NOI18N
        labelResultadosTitle.setForeground(new java.awt.Color(228, 214, 167));
        labelResultadosTitle.setText("RESULTADOS");
        panelResultados.add(labelResultadosTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        btnResultadosSig.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnResultadosSig.setIcon(new ImageIcon("src/main/resources/imagenes/iconos/derecha.png"));
        btnResultadosSig.setImgHovered(new ImageIcon("src/main/resources/imagenes/iconos/derecha_hover.png"));
        btnResultadosSig.setImgOriginal(new ImageIcon("src/main/resources/imagenes/iconos/derecha.png"));
        btnResultadosSig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResultadosSigMouseClicked(evt);
            }
        });
        panelResultados.add(btnResultadosSig, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 60, 50));

        mainPanel.add(panelResultados, "resultados");

        labelTitulo.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(228, 214, 167));
        labelTitulo.setText("MEMORAMA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(labelTitulo)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(labelTitulo)
                .addGap(18, 18, 18)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnResultadosSigMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResultadosSigMouseClicked
        avanzarCarta();
    }//GEN-LAST:event_btnResultadosSigMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private uabc.ic.benjaminbolanos.practica5.BotonLabel btnResultadosSig;
    private uabc.ic.benjaminbolanos.practica5.memorama.CartaGrafica cartaGrafica1;
    private javax.swing.JLabel labelResultadosTitle;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelTitulo1;
    private javax.swing.JLabel labelTitulo10;
    private javax.swing.JLabel labelTitulo2;
    private javax.swing.JLabel labelTitulo3;
    private javax.swing.JLabel labelTitulo4;
    private javax.swing.JLabel labelTitulo5;
    private javax.swing.JLabel labelTitulo6;
    private javax.swing.JLabel labelTitulo7;
    private javax.swing.JLabel labelTitulo8;
    private javax.swing.JLabel labelTitulo9;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelGuia;
    private javax.swing.JPanel panelResultados;
    // End of variables declaration//GEN-END:variables
}
