package uabc.ic.benjaminbolanos.practica5.memorama;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author bbola
 */
public class VistaMemorama extends javax.swing.JPanel {

    private final ControlMemorama control;

    private int cantidadCartasSeleccionadas;

    private final CartaGrafica[] cartasSeleccionadas;
    private final int[] posicionesCartasSeleccionadas;
    private CartaGrafica[] cartasGraficas;

    /**
     * Creates new form VistaMemorama
     */
    public VistaMemorama() {
        initComponents();
        control = new ControlMemorama();
        crearArrayCartas();
        cartasSeleccionadas = new CartaGrafica[2];
        posicionesCartasSeleccionadas = new int[2];
        configurarCartas();
        nuevoJuego();
    }
    
    private void nuevoJuego(){
        control.crearCartas();
        cantidadCartasSeleccionadas = 0;
        var cartasModel = control.getCartas();
        for(int i = 0; i < cartasGraficas.length; i++){
            cartasGraficas[i].setVisible(true);
            cartasGraficas[i].mostrarReverso();
            cartasGraficas[i].setContenido(cartasModel[i]);
        }
        botonJuegoNuevo.setVisible(false);
        panelResultados.mostrarGuia();
    }
    
    private void crearArrayCartas(){
        cartasGraficas = new CartaGrafica[]{
            cartaGrafica1, cartaGrafica2, cartaGrafica3, cartaGrafica4,
            cartaGrafica5, cartaGrafica6, cartaGrafica7, cartaGrafica8
        };
    }

    private void cartasListener(int posCarta, CartaGrafica carta) {
        if (cantidadCartasSeleccionadas < 2) {
            carta.mostrarContenido();
            cartasSeleccionadas[cantidadCartasSeleccionadas] = carta;
            posicionesCartasSeleccionadas[cantidadCartasSeleccionadas++] = posCarta;
        }
    }
    
    private void configurarCartas() {
        for (int i = 0; i < cartasGraficas.length; i++) {
            int pos = i;
            CartaGrafica carta = cartasGraficas[i];
            cartasGraficas[i].addMouseListener(new MouseAdapter(){
                @Override
                public void mouseClicked(MouseEvent e){
                    cartasListener(pos, carta);
                }
            });
        }
    }
    private void realizarIntento() {
        if (cantidadCartasSeleccionadas == 2) {
            System.out.println("Intercambio entre: " + posicionesCartasSeleccionadas[0] + " - " + posicionesCartasSeleccionadas[1]);
            if (control.sonPares(posicionesCartasSeleccionadas[0], posicionesCartasSeleccionadas[1])) {
                cartasSeleccionadas[0].setVisible(false);
                cartasSeleccionadas[1].setVisible(false);
            } else {
                cartasSeleccionadas[0].mostrarReverso();
                cartasSeleccionadas[1].mostrarReverso();
            }
            cantidadCartasSeleccionadas = 0;
            
            if(control.juegoTerminado()){
                panelResultados.mostrarResultados(control.getCartasAceptadas());
                botonJuegoNuevo.setVisible(true);
            }
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPanel = new javax.swing.JPanel();
        cartaGrafica1 = new uabc.ic.benjaminbolanos.practica5.memorama.CartaGrafica();
        cartaGrafica2 = new uabc.ic.benjaminbolanos.practica5.memorama.CartaGrafica();
        cartaGrafica3 = new uabc.ic.benjaminbolanos.practica5.memorama.CartaGrafica();
        cartaGrafica4 = new uabc.ic.benjaminbolanos.practica5.memorama.CartaGrafica();
        cartaGrafica5 = new uabc.ic.benjaminbolanos.practica5.memorama.CartaGrafica();
        cartaGrafica6 = new uabc.ic.benjaminbolanos.practica5.memorama.CartaGrafica();
        cartaGrafica7 = new uabc.ic.benjaminbolanos.practica5.memorama.CartaGrafica();
        cartaGrafica8 = new uabc.ic.benjaminbolanos.practica5.memorama.CartaGrafica();
        botonRealizarIntento = new javax.swing.JButton();
        botonJuegoNuevo = new javax.swing.JButton();
        panelResultados = new uabc.ic.benjaminbolanos.practica5.memorama.PanelResultadosMemorama();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        contentPanel.setBackground(new java.awt.Color(228, 214, 167));
        contentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        contentPanel.add(cartaGrafica1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));
        contentPanel.add(cartaGrafica2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));
        contentPanel.add(cartaGrafica3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, -1, -1));
        contentPanel.add(cartaGrafica4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, -1, -1));
        contentPanel.add(cartaGrafica5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, -1, -1));
        contentPanel.add(cartaGrafica6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, -1, -1));
        contentPanel.add(cartaGrafica7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, -1, -1));
        contentPanel.add(cartaGrafica8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 440, -1, -1));

        botonRealizarIntento.setBackground(new java.awt.Color(28, 17, 10));
        botonRealizarIntento.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        botonRealizarIntento.setForeground(new java.awt.Color(228, 214, 167));
        botonRealizarIntento.setText("Realizar Intento");
        botonRealizarIntento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRealizarIntentoActionPerformed(evt);
            }
        });
        contentPanel.add(botonRealizarIntento, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 710, 170, 40));

        botonJuegoNuevo.setBackground(new java.awt.Color(28, 17, 10));
        botonJuegoNuevo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        botonJuegoNuevo.setForeground(new java.awt.Color(228, 214, 167));
        botonJuegoNuevo.setText("Nuevo Juego");
        botonJuegoNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonJuegoNuevoActionPerformed(evt);
            }
        });
        contentPanel.add(botonJuegoNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 710, 170, 40));
        contentPanel.add(panelResultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, -1, -1));

        jPanel1.setBackground(new java.awt.Color(28, 17, 10));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        contentPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 20));

        jPanel2.setBackground(new java.awt.Color(28, 17, 10));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        contentPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 780, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonRealizarIntentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRealizarIntentoActionPerformed
        realizarIntento();
    }//GEN-LAST:event_botonRealizarIntentoActionPerformed

    private void botonJuegoNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonJuegoNuevoActionPerformed
        nuevoJuego();
    }//GEN-LAST:event_botonJuegoNuevoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonJuegoNuevo;
    private javax.swing.JButton botonRealizarIntento;
    private uabc.ic.benjaminbolanos.practica5.memorama.CartaGrafica cartaGrafica1;
    private uabc.ic.benjaminbolanos.practica5.memorama.CartaGrafica cartaGrafica2;
    private uabc.ic.benjaminbolanos.practica5.memorama.CartaGrafica cartaGrafica3;
    private uabc.ic.benjaminbolanos.practica5.memorama.CartaGrafica cartaGrafica4;
    private uabc.ic.benjaminbolanos.practica5.memorama.CartaGrafica cartaGrafica5;
    private uabc.ic.benjaminbolanos.practica5.memorama.CartaGrafica cartaGrafica6;
    private uabc.ic.benjaminbolanos.practica5.memorama.CartaGrafica cartaGrafica7;
    private uabc.ic.benjaminbolanos.practica5.memorama.CartaGrafica cartaGrafica8;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private uabc.ic.benjaminbolanos.practica5.memorama.PanelResultadosMemorama panelResultados;
    // End of variables declaration//GEN-END:variables
}
