package uabc.ic.benjaminbolanos.practica5.listaculturas;

import uabc.ic.benjaminbolanos.practica5.Cultura;

/**
 * Clase que modela el ambiente gráfico donde se muestra la informacion
 * de una Cultura.
 * @author benjabolanos
 */
public class PanelCulturas extends javax.swing.JPanel {
    
    public PanelCulturas() {
        initComponents();
    }
    
    /**
     * Método que cambia los valores de los labels para mostrar la 
     * información de una cultura.
     * @param cultura Cultura de la cual se mostrarán sus datos.
     */
    public void setCultura(Cultura cultura){
        labelCultura.setText(cultura.getNombre());
        txtArea.setText("<html>"+cultura.getAreaGeografica()+"</html>");
        txtCiudad.setText(cultura.getCiudadPrincipal());
        txtEpoca.setText(cultura.getAñoAparicion()+" - "+cultura.getAñoExtincion());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelCultura = new javax.swing.JLabel();
        labelCiudad = new javax.swing.JLabel();
        labelCiudad2 = new javax.swing.JLabel();
        labelArea = new javax.swing.JLabel();
        labelEpoca = new javax.swing.JLabel();
        sep1 = new javax.swing.JSeparator();
        sep2 = new javax.swing.JSeparator();
        sep3 = new javax.swing.JSeparator();
        sep4 = new javax.swing.JSeparator();
        txtCiudad = new javax.swing.JLabel();
        txtEpoca = new javax.swing.JLabel();
        txtArea = new javax.swing.JLabel();
        labelCultura1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(228, 214, 167));
        setForeground(new java.awt.Color(220, 190, 140));
        setMaximumSize(new java.awt.Dimension(900, 800));
        setMinimumSize(new java.awt.Dimension(900, 800));
        setPreferredSize(new java.awt.Dimension(900, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelCultura.setFont(new java.awt.Font("Hardenburg Demo", 1, 64)); // NOI18N
        labelCultura.setForeground(new java.awt.Color(28, 17, 10));
        labelCultura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCultura.setText("Olmeca");
        labelCultura.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        labelCultura.setAlignmentY(0.0F);
        labelCultura.setFocusTraversalPolicyProvider(true);
        labelCultura.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelCultura.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        add(labelCultura, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 490, 120));

        labelCiudad.setFont(new java.awt.Font("Cinzel Decorative", 1, 24)); // NOI18N
        labelCiudad.setForeground(new java.awt.Color(28, 17, 10));
        labelCiudad.setText("Ciudad");
        add(labelCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));

        labelCiudad2.setFont(new java.awt.Font("Cinzel Decorative", 1, 24)); // NOI18N
        labelCiudad2.setForeground(new java.awt.Color(28, 17, 10));
        labelCiudad2.setText("más importante");
        add(labelCiudad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        labelArea.setFont(new java.awt.Font("Cinzel Decorative", 1, 24)); // NOI18N
        labelArea.setForeground(new java.awt.Color(28, 17, 10));
        labelArea.setText("Area Geografica");
        add(labelArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, -1, -1));

        labelEpoca.setFont(new java.awt.Font("Cinzel Decorative", 1, 24)); // NOI18N
        labelEpoca.setForeground(new java.awt.Color(28, 17, 10));
        labelEpoca.setText("Epoca");
        add(labelEpoca, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 610, -1, -1));

        sep1.setBackground(new java.awt.Color(64, 44, 0));
        sep1.setForeground(new java.awt.Color(28, 17, 10));
        sep1.setOpaque(true);
        add(sep1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 270, 1));

        sep2.setBackground(new java.awt.Color(64, 44, 0));
        sep2.setForeground(new java.awt.Color(28, 17, 10));
        sep2.setOpaque(true);
        add(sep2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 640, 110, 1));

        sep3.setBackground(new java.awt.Color(64, 44, 0));
        sep3.setForeground(new java.awt.Color(28, 17, 10));
        sep3.setOpaque(true);
        add(sep3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 280, 1));

        sep4.setBackground(new java.awt.Color(64, 44, 0));
        sep4.setForeground(new java.awt.Color(28, 17, 10));
        sep4.setOpaque(true);
        add(sep4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, 370, 1));

        txtCiudad.setFont(new java.awt.Font("Cinzel Decorative", 1, 36)); // NOI18N
        txtCiudad.setForeground(new java.awt.Color(28, 17, 10));
        txtCiudad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCiudad.setText("La Venta");
        add(txtCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 410, -1));

        txtEpoca.setFont(new java.awt.Font("Cinzel Decorative", 1, 36)); // NOI18N
        txtEpoca.setForeground(new java.awt.Color(28, 17, 10));
        txtEpoca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtEpoca.setText("3000 a.C. - 400 a.C.");
        add(txtEpoca, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 660, 430, -1));

        txtArea.setFont(new java.awt.Font("Cinzel Decorative", 1, 36)); // NOI18N
        txtArea.setForeground(new java.awt.Color(28, 17, 10));
        txtArea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtArea.setText("<html>Costa del Golfo de México</html>");
        txtArea.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        txtArea.setFocusable(false);
        txtArea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(txtArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 320, 180));

        labelCultura1.setFont(new java.awt.Font("Hardenburg Demo", 1, 36)); // NOI18N
        labelCultura1.setForeground(new java.awt.Color(28, 17, 10));
        labelCultura1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCultura1.setText("Cultura");
        labelCultura1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(labelCultura1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 490, 90));

        jPanel1.setBackground(new java.awt.Color(28, 17, 10));
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 20));

        jPanel3.setBackground(new java.awt.Color(28, 17, 10));
        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 780, 900, 20));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelArea;
    private javax.swing.JLabel labelCiudad;
    private javax.swing.JLabel labelCiudad2;
    private javax.swing.JLabel labelCultura;
    private javax.swing.JLabel labelCultura1;
    private javax.swing.JLabel labelEpoca;
    private javax.swing.JSeparator sep1;
    private javax.swing.JSeparator sep2;
    private javax.swing.JSeparator sep3;
    private javax.swing.JSeparator sep4;
    private javax.swing.JLabel txtArea;
    private javax.swing.JLabel txtCiudad;
    private javax.swing.JLabel txtEpoca;
    // End of variables declaration//GEN-END:variables
}
